name: githubpush
on:
  workflow_dispatch:

jobs:
  binaries:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - run: make binaries

    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: binaries


  ghcr:
    needs: binaries
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: binaries
        path: binaries

    - run: make githubcontainer
      env:
        G_username: ${{ github.actor }}
        G_password: ${{ secrets.GITHUB_TOKEN }}
